services:
  backend:
    build: ./backend
    ports:
      - 3001:3001 #local:container
    env_file: ./backend/.env
  db:
    image: postgres
    # restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - 3000:3000 #local:container
