services:
  backend:
    build: ./backend
    ports:
      - 3001:3001 #local:container
    volumes:
      - ./backend/src:/app/src
    env_file: ./backend/.env
  db:
    image: postgres
    # restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - .env

  # En dev, on lance le front à la main à côté, mais si besoin on peut tout lancer via le docker compose en décommentant ci-dessous
  # frontend:
  #   build: ./frontend
  #   command: npm run dev
  #   ports:
  #     - 3000:3000 #local:container
  #   volumes:
  #     - ./frontend/src:/app/src
