GET http://localhost:3001/ads

###

GET http://localhost:3001/ads/1

###


POST http://localhost:3001/ads
content-Type: application/json

{
  "title": "Tesla",
  "description":
      "Tesla rouge à vendre",
  "owner": "tesla.vendeur@gmail.com",
  "price": 40000,
  "picture": "https://mcdn.wallpapersafari.com/335/69/61/VRkYd3.jpg",
  "location": "Lille",
  "category": { "id": 7 },
  "tags": [{"id": 2}]
}

###

PATCH http://localhost:3001/ads/3
content-Type: application/json

{
  "title": "Fiat Multipla"
}

###

DELETE http://localhost:3001/ads/14

###

GET http://localhost:3001/categories

###

GET http://localhost:3001/categories/1

###

GET http://localhost:3001/categories/7/ads

###

POST http://localhost:3001/categories
content-Type: application/json

{
  "name": "Vacances"
}

###

PATCH http://localhost:3001/categories/4
content-Type: application/json

{
    "name": "clothes"
  }

###

DELETE http://localhost:3001/categories/3

###

GET http://localhost:3001/tags

###

POST http://localhost:3001/tags
content-Type: application/json

{
  "name": "Satisfaisant"
}

###

PATCH http://localhost:3001/tags/1
content-Type: application/json

{
    "name": "brand new"
  }

###

DELETE http://localhost:3001/tags/3